<?php $title='Stock Operations';$subtitle='Propose, independently approve, then post stock changes.';$toolbar='<a class="button-primary" href="/inventory-operations/create">Create Proposal</a><a class="button" href="/replenishment">Replenishment</a>';require __DIR__.'/start.php'; ?>
<form method="get" action="/inventory-operations" class="filters">
<label>Search reason <input name="q" maxlength="120" value="<?= $escape($filters['q']) ?>"></label>
<label>Type <select name="kind"><option value="">All types</option><?php foreach(\App\Service\BusinessOperationService::KINDS as $kind): ?><option value="<?= $kind ?>" <?= $filters['kind']===$kind?'selected':'' ?>><?= $escape($kind) ?></option><?php endforeach; ?></select></label>
<label>Status <select name="status"><option value="">All statuses</option><?php foreach(\App\Service\BusinessOperationService::STATUSES as $state): ?><option value="<?= $state ?>" <?= $filters['status']===$state?'selected':'' ?>><?= $escape($state) ?></option><?php endforeach; ?></select></label>
<button type="submit">Apply Filters</button><a class="button" href="/inventory-operations">Reset</a>
</form>
<?php if($result!==null): ?><section class="table-scroll" aria-label="Stock operations table"><table class="data-table"><thead><tr><th>Operation</th><th>Type</th><th>Warehouse</th><th>Creator</th><th>Status</th><th>Date</th></tr></thead><tbody>
<?php foreach($result->items() as $row): ?><tr><td><a href="/inventory-operations/show?id=<?= (int)$row['id'] ?>">#<?= (int)$row['id'] ?></a></td><td><?= $escape($row['kind']) ?></td><td><?= $escape($row['warehouse_name']) ?><?= $row['destination_name']!==null?' → '.$escape($row['destination_name']):'' ?></td><td><?= $escape($row['creator_email']) ?></td><td><span class="status-badge <?= match($row['status']){'Posted'=>'status-success','Cancelled','Rejected'=>'status-danger',default=>'status-pending'} ?>"><?= $escape($row['status']) ?></span></td><td><?= $escape($row['created_at']) ?></td></tr><?php endforeach; ?>
<?php if($result->total()===0): ?><tr><td colspan="6">No operations match these filters.</td></tr><?php endif; ?>
</tbody></table></section><?php $paginationPath='/inventory-operations';$paginationLabel='Operations';$paginationQuery=$filters;require dirname(__DIR__).'/partials/pagination.php';endif;require __DIR__.'/end.php'; ?>
