<fieldset data-stock-item class="stock-proposal-item"><legend>Product item</legend>
<label class="field" data-stock-field="regular"><span class="field-label">Product</span><select data-stock-input="product_id" name="<?= $escape($prefix) ?>product_id<?= $prefix!==''?']':'' ?>"><?php foreach($products as $product): ?><option value="<?= $product->id() ?>" <?= $itemState->selected('product_id',$product->id(),false) ?>><?= $escape($product->sku().' — '.$product->name()) ?></option><?php endforeach; ?></select></label>
<label class="field" data-stock-field="adjustment"><span class="field-label">Stock baseline at count</span><input data-stock-input="baseline" name="<?= $escape($prefix) ?>baseline<?= $prefix!==''?']':'' ?>" type="number" min="0" readonly value="<?= $escape($itemState->value('baseline','')) ?>"></label>
<label class="field" data-stock-field="return"><span class="field-label">Original receipt/issue ledger ID</span><input data-stock-input="source_ledger_id" name="<?= $escape($prefix) ?>source_ledger_id<?= $prefix!==''?']':'' ?>" inputmode="numeric" value="<?= $escape($itemState->value('source_ledger_id','')) ?>"></label>
<output data-stock-source-summary></output>
<label class="field"><span class="field-label" data-stock-quantity-label>Counted Quantity</span><input data-stock-input="quantity" name="<?= $escape($prefix) ?>quantity<?= $prefix!==''?']':'' ?>" type="number" min="0" max="4294967295" required value="<?= $escape($itemState->value('quantity','')) ?>"></label>
<label class="field" data-stock-field="customer"><span><input type="checkbox" data-stock-input="fit_for_stock" name="<?= $escape($prefix) ?>fit_for_stock<?= $prefix!==''?']':'' ?>" value="1" <?= $itemState->value('fit_for_stock','')==='1'?'checked':'' ?>> Returned goods are fit to re-enter stock.</span></label>
<button type="button" class="button button-quiet" data-stock-remove <?= $prefix===''?'disabled':'' ?>>Remove item</button>
</fieldset>
