<?php $title='Replenishment';$subtitle='Suggested quantity = reorder point minus stock minus open PO supply, per warehouse.';$toolbar='<a class="button-primary" href="/purchase-orders/create">Create PO</a>';require __DIR__.'/start.php';$selecting=$filters['warehouse_id']!==''; ?>
<?php if($result!==null && !$selecting): ?><p class="page-subtitle">Choose one warehouse to select several recommendations for a single purchase order.</p><?php endif; ?>
<form method="get" action="/replenishment" class="filters"><label>Search product <input name="q" maxlength="120" value="<?= $escape($filters['q']) ?>"></label>
<label>Warehouse <select name="warehouse_id"><option value="">All warehouses</option><?php foreach($warehouses as $warehouse): ?><option value="<?= $warehouse->id() ?>" <?= $filters['warehouse_id']===(string)$warehouse->id()?'selected':'' ?>><?= $escape($warehouse->name()) ?></option><?php endforeach; ?></select></label>
<button type="submit">Apply Filters</button><a class="button" href="/replenishment">Reset</a></form>
<?php if($result!==null): ?>
<div class="table-scroll" role="region" aria-label="Replenishment table" tabindex="0"><table class="data-table"><thead><tr><?php if($selecting): ?><th scope="col" data-no-sort>Select</th><?php endif; ?><th>Product</th><th>Warehouse</th><th>Stock</th><th>Reorder point</th><th>Open PO supply</th><th>Suggested</th><th>Action</th></tr></thead><tbody>
<?php foreach($result->items() as $row): ?><tr><?php if($selecting): ?><td><input type="checkbox" form="replenishment-selection" name="pick[]" value="<?= (int)$row['product_id'].':'.(int)$row['suggested'] ?>" aria-label="<?= $escape('Select '.$row['sku']) ?>"></td><?php endif; ?><td><?= $escape($row['sku'].' — '.$row['product_name']) ?></td><td><?= $escape($row['warehouse_name']) ?></td><td><?= (int)$row['quantity'] ?></td><td><?= (int)$row['reorder_point'] ?></td><td><?= (int)$row['inbound'] ?></td><td><?= (int)$row['suggested'] ?></td><td><a class="action-link" href="<?= $escape('/purchase-orders/create?'.http_build_query(['product_id'=>$row['product_id'],'warehouse_id'=>$row['warehouse_id'],'quantity'=>$row['suggested']])) ?>">Review PO</a></td></tr><?php endforeach; ?>
<?php if($result->total()===0): ?><tr><td colspan="<?= $selecting?8:7 ?>">No products need additional supply.</td></tr><?php endif; ?></tbody></table></div>
<?php $paginationPath='/replenishment';$paginationLabel='Recommendations';$paginationQuery=['q'=>$filters['q'],'warehouse_id'=>$filters['warehouse_id']];require dirname(__DIR__).'/partials/pagination.php'; ?>
<?php if($selecting && $result->total()>0): ?><form method="get" action="/purchase-orders/create" id="replenishment-selection" data-replenishment-selection><input type="hidden" name="warehouse_id" value="<?= $escape($filters['warehouse_id']) ?>"><div class="form-actions"><button type="submit">Review PO for selected</button><span class="page-subtitle">Supplier, quantities and prices are reviewed before the draft is saved.</span></div></form><?php endif; ?>
<?php endif;require __DIR__.'/end.php'; ?>
