<?php $title=$operation['kind'].' #'.$operation['id'];$subtitle='Stock changes are applied only after independent approval.';$toolbar='<a class="button" href="/timeline?kind=Operation&amp;id='.(int)$operation['id'].'">Transaction Timeline</a><a class="button" href="/inventory-operations">Stock Operations</a>';require __DIR__.'/start.php'; ?>
<section class="card"><div class="card-body"><p>Status: <span class="status-badge <?= $operation['status']==='Posted'?'status-success':(in_array($operation['status'],['Rejected','Cancelled'],true)?'status-danger':'status-pending') ?>"><?= $escape($operation['status']) ?></span></p><p>Reason: <?= $escape($operation['reason']) ?></p><p>Source warehouse #<?= (int)$operation['warehouse_id'] ?><?= $operation['destination_id']!==null?' → destination #'.(int)$operation['destination_id']:'' ?></p><p>Created by #<?= (int)$operation['created_by'] ?><?php if($operation['approved_by']!==null): ?> · Reviewed by #<?= (int)$operation['approved_by'] ?><?php endif; ?><?php if($operation['posted_by']!==null): ?> · Posted by #<?= (int)$operation['posted_by'] ?><?php endif; ?></p><?php if($operation['decision_reason']!==null): ?><p>Review/cancellation reason: <?= $escape($operation['decision_reason']) ?></p><?php endif; ?><?php if($operation['kind']==='CustomerReturn'): ?><p>Returned goods confirmed fit for stock.</p><?php endif; ?></div></section>
<section class="table-scroll" aria-label="Operation items"><table class="data-table"><thead><tr><th>Product</th><th><?= $operation['kind']==='Adjustment'?'Counted quantity':'Quantity' ?></th><th>Count baseline</th><th>Original ledger</th></tr></thead><tbody><?php foreach($operation['items'] as $item): ?><tr><td><?= $escape($item['sku'].' — '.$item['product_name']) ?></td><td><?= (int)$item['quantity'] ?></td><td><?= $item['baseline']===null?'—':(int)$item['baseline'] ?></td><td><?= $item['source_ledger_id']===null?'—':'#'.(int)$item['source_ledger_id'] ?></td></tr><?php endforeach; ?></tbody></table></section>
<?php if($operation['status']==='PendingApproval' && $actor->role()==='Admin' && $actor->userId()!==(int)$operation['created_by']): ?>
<form method="post" action="/inventory-operations/decide" class="form"><input type="hidden" name="csrf_token" value="<?= $escape($GLOBALS['csrf_token']??'') ?>"><input type="hidden" name="id" value="<?= (int)$operation['id'] ?>"><label class="field"><span class="field-label">Approval reason</span><textarea name="reason" maxlength="500" required></textarea></label><div class="form-actions"><button type="button" class="button-danger" data-dialog-open="reject-dialog">Reject</button><button type="submit" name="decision" value="Approved">Approve</button></div></form>
<?php $dialog=['id'=>'reject-dialog','title'=>'Reject '.$operation['kind'].' #'.(int)$operation['id'],'intro'=>'The proposal is closed as Rejected and no stock changes are made. The reason is shown on this page and in the timeline.','action'=>'/inventory-operations/decide','hidden'=>['id'=>(int)$operation['id'],'decision'=>'Rejected'],'label'=>'Rejection reason','submit'=>'Reject Proposal']+($rejectDialog??[]);require dirname(__DIR__).'/partials/reason-dialog.php'; ?>
<?php endif; ?>
<?php if($operation['status']==='PendingApproval' && $actor->userId()===(int)$operation['created_by']): ?><p class="alert">Another Admin must review this proposal.</p><?php endif; ?>
<?php if($operation['status']==='Approved'): ?><form method="post" action="/inventory-operations/post" class="form"><input type="hidden" name="csrf_token" value="<?= $escape($GLOBALS['csrf_token']??'') ?>"><input type="hidden" name="id" value="<?= (int)$operation['id'] ?>"><div class="form-actions"><button type="submit">Post Stock Changes</button></div></form><?php endif; ?>
<?php if(in_array($operation['status'],['PendingApproval','Approved'],true) && ($actor->role()==='Admin'||$actor->userId()===(int)$operation['created_by'])): ?><form method="post" action="/inventory-operations/decide" class="form"><input type="hidden" name="csrf_token" value="<?= $escape($GLOBALS['csrf_token']??'') ?>"><input type="hidden" name="id" value="<?= (int)$operation['id'] ?>"><input type="hidden" name="decision" value="Cancelled"><label class="field"><span class="field-label">Cancellation reason</span><textarea name="reason" maxlength="500" required></textarea></label><div class="form-actions"><button type="submit" class="button button-quiet">Cancel Proposal</button></div></form><?php endif; ?>
<?php require __DIR__.'/end.php'; ?>
